/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "isr_uart_rx.h"
#include "P2_3_aliases.h"
#include "P2_3.h"
#include "P2_4_aliases.h"
#include "P2_4.h"
#include "P2_5_aliases.h"
#include "P2_5.h"
#include "P2_6_aliases.h"
#include "P2_6.h"
#include "P3_3_aliases.h"
#include "P3_3.h"
#include "P3_4_aliases.h"
#include "P3_4.h"
#include "P3_5_aliases.h"
#include "P3_5.h"
#include "P3_6_aliases.h"
#include "P3_6.h"
#include "PWM.h"
#include "LED_aliases.h"
#include "LED.h"
#include "isr_PWM.h"
#include "Control_Reg_1.h"
#include "Clock_2.h"
#include "LED_1_aliases.h"
#include "LED_1.h"
#include "sensorClk_aliases.h"
#include "sensorClk.h"
#include "sensorSignal_aliases.h"
#include "sensorSignal.h"
#include "sensorReset_aliases.h"
#include "sensorReset.h"
#include "ServoPWM.h"
#include "servoControl_aliases.h"
#include "servoControl.h"
#include "ServoClk.h"
#include "magnetControl_aliases.h"
#include "magnetControl.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

